export enum MessageID {
    INVALID,
    AUTHENTICATE,
    AUTHENTICATION_FAILED,
    AUTHENTICATION_SUCCEEDED,
    REQUEST,
    RESPONSE,
    PLAYER_CAME_ONLINE,
    PLAYER_WENT_OFFLINE,
    FORWARD,
    GET_PLAYERS,
    ICE,
    SDP,
    CHAT_MESSAGE,
    MATCHMAKE,
    MATCHMAKE_SUCCESS
}